# System Timestamp: 2025-11-29 13:19:26.933797
appId: com.fortuna.faucet
productName: "Fortuna Faucet"
artifactName: "Fortuna-Faucet-${version}-${arch}.${ext}"
directories:
  app: "."
  buildResources: "assets"
  output: "dist"
files:
  - "main.js"
  - "preload.js"
  - "secure-settings-manager.js"
  - "package.json"
  - "web-ui-build/**/*"
  - "assets/**/*"
  - "!**/node_modules/*/{test,__mocks__,__tests__}/**"
extraResources:
  - from: "resources/fortuna-backend.exe"
    to: "fortuna-backend.exe"
asar: true
protocols:
  - name: "Fortuna Faucet Protocol"
    schemes:
      - "fortuna"
fileAssociations:
  - ext: "faucet"
    name: "Fortuna Project File"
    role: "Editor"
    description: "Opens Fortuna Faucet project payloads"
icon: assets/icon.ico
win:
  target:
    - target: "msi"
      arch:
        - x64
  legalTrademarks: "Fortuna Labs"
  publisherName:
    - "Fortuna Labs LLC"
msi:
  installerIcon: assets/icon.ico
  uninstallerIcon: assets/icon.ico
  oneClick: false
  perMachine: true
  runAfterFinish: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: "Fortuna Faucet"
  warningsAsErrors: true
publish: []
