appId: com.fortuna.faucet
productName: "Fortuna Faucet"
directories:
  buildResources: "__ABSOLUTE_PATH__/electron/assets"
  output: "dist"
files:
  - "**/*"
  - "!node_modules/**/*"
  - "!dist/**/*"
extraResources:
  - from: "__ABSOLUTE_PATH__/electron/resources/fortuna-backend.exe"
    to: "fortuna-backend.exe"
win:
  target: "msi"
  icon: "__ABSOLUTE_PATH__/electron/assets/icon.ico"
msi:
  oneClick: false
  perMachine: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: "Fortuna Faucet"
