appId: com.fortuna.faucet
productName: "Fortuna Faucet"
directories:
  buildResources: "assets"
  output: "dist"
files:
  - "main.js"
  - "preload.js"
  - "package.json"
  - "web-ui-build/out/**/*"
  - "assets/**/*"
extraResources:
  - from: "resources/fortuna-backend.exe"
    to: "fortuna-backend.exe"
win:
  target: "msi"
  icon: "assets/icon.ico"
msi:
  oneClick: false
  perMachine: true
  runAfterFinish: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: "Fortuna Faucet"
  menuCategory: "Fortuna Faucet"
