name: âš¡ Release (Hat-Trick)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-core:
    uses: ./.github/workflows/build-core-universal.yml
    with:
      enable_forensics: false
      enable_dietician: false
      enable_canary: false
      enable_paparazzi: false
    secrets: inherit
